ddm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('newapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                     document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                     document_root=settings.MEDIA_ROOT)

ddmapp/urls.py
from django.urls import path
from .import views

app_name='ddmapp'


urlpatterns = [

    path('',views.department,name='department'),


    ]

newapp/urls.py
from django.urls import path

from . import views

app_name='newapp'

urlpatterns = [

    path('', views.department, name='department'),
    path('<slug:c_slug>', views.department, name='department_by_course'),
    path('<slug:c_slug>/<slug:dept_slug>/', views.deptdetail, name='deptcourcedetail'),
    path('add', views.CreateView, name='add'),
    path('<int:pk>/', views.UpdateView, name='change'),
]

ddmapp/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.urls import reverse


# Create your models here.
class Course(models.Model):
    name=models.CharField(max_length=250,unique=True)

    def __str__(self):
        return '{}'.format(self.name)

class Department(models.Model):
    name=models.CharField(max_length=250,unique=True)
    course=models.ForeignKey(Course,on_delete=models.CASCADE)


    def __str__(self):
        return '{}'.format(self.name)

newapp/models.py
from django.db import models


# Create your models here.
from django.urls import reverse


class Purpose(models.Model):
    name=models.CharField(max_length=120)
    def __str__(self):
        return self.name

class Course(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'course'
        verbose_name_plural = 'course'

    def get_url(self):
        return reverse('newapp:department_by_course', args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)


class Department(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    course=models.ForeignKey(Course,on_delete=models.CASCADE)

    def get_url(self):
        return reverse('newapp:deptcourcedetail',args=[self.course.slug,self.slug])


    class Meta:
        ordering=('name',)
        verbose_name='department'
        verbose_name_plural='departments'

    def __str__(self):
        return '{}'.format(self.name)




class Form(models.Model):
    name = models.CharField(max_length=124)
    dob= models.DateField(null=True,blank=True)
    age= models.IntegerField()
    gender=models.CharField(max_length=120)
    phn=models.IntegerField()
    email=models.EmailField()
    address=models.TextField(blank=True)
    department = models.ForeignKey(Department,on_delete=models.SET_NULL,null=True)
    course = models.ForeignKey(Course,on_delete=models.SET_NULL,null=True)
    Purpose=models.ForeignKey(Purpose,on_delete=models.SET_NULL,null=True)
    debit=models.BooleanField("Debit",default=False)
    note_book=models.BooleanField("Note_Book",default=False)
    pen = models.BooleanField("Pen", default=False)
    exam_papper = models.BooleanField("Exam_papper", default=False)

    def __str__(self):
        return self.name

newapp/forms.py
from django import forms
from newapp.models import Form


class StudentForm(forms.ModelForm):
    class Meta:
        model = Form
        fields = ['name','dob','age','gender','phn','email','address','department','course','Purpose','debit','note_book','pen','exam_papper']

ddmapp/views.py
from django.shortcuts import render

# Create your views here.
from .models import Department,Course
def department(request):
    courseid=request.GET.get('course',None)
    departmentid = request.GET.get('department', None)
    department=None
    if courseid:
        getcourse=Course.objects.get(id=courseid)
        department=Department.objects.filter(course=getcourse)
    if departmentid:
        getdepartment = Course.objects.get(id=departmentid)

    course=Course.objects.all()
    return render(request,'form.html',locals())

newapp/views.py
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404

from newapp.forms import StudentForm
from newapp.models import Purpose,Form, Department,Course

from django.shortcuts import render

# Create your views here.

def department(request):
    courseid=request.GET.get('course',None)
    departmentid = request.GET.get('department', None)
    department=None
    if courseid:
        getcourse=Course.objects.get(id=courseid)
        department=Department.objects.filter(course=getcourse)
    if departmentid:
        getdepartment = Course.objects.get(id=departmentid)
        course=Course.objects.all()

    return render(request,'ddm.html',locals())







def department(request):
    def department(request, c_slug=None):
        c_page = None
        dept = None
        if c_slug != None:
            c_page = get_object_or_404(Course, slug=c_slug)
            dept = Department.objects.all().filter(course=c_page, available=True)
        else:
            dept = Department.objects.all().filter(available=True)
        return render(request, "ddm.html", {'course': c_page, 'dept': dept})

def deptdetail(request, c_slug, dept_slug):
        try:
            dept = Department.objects.get(course__slug=c_slug, slug=dept_slug)
        except Exception as e:
            raise e
        return render(request, 'ddm.html', {'dept': dept})
def CreateView(request):
    form=StudentForm()
    if request.method=='POST':
        form=StudentForm(request.POST)
        if form.is_valid():
            form.save()
            messages.info(request, "order confirmed")
            return redirect('new:add')
    return render(request,'form.html',{'form':form})

def UpdateView(request,pk):
    student = get_object_or_404(Form, pk=pk)
    form=StudentForm(instance=student)
    if request.method=='POST':
        form=StudentForm(request.POST)
        if form.is_valid():
            form.save()
            messages.info(request, "order confirmed")
            return redirect('new:change')
    return render(request,'form.html',{'form':form})

templates/ddm.html
{% load static %}

<div class="container" >

        {% for d in dept %}
            <a href="{{d.get_url}}"><img class="card-img-top my_image" src="{{d.image.url}}" alt="{{d.name}}"></a>
        <h4>{{d.name}}</h4>
</div>
        {% endfor %}
    </div>
</div>


<div class="row my_prod_row_class">
    <div class="mx_auto">
        <p><a href="{% url 'newapp:department' %}">Home</a>| <a href="{{dept.course.get_url}}" >{{dept.course}}</a>|{{dept.name}}</p>
    </div>
<div  class="container">
<br>
<div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <div style="min-width:18rem">
            <img src="{{dept.image.url}}" alt="{{dept.name}}">
        </div>
    </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6">
        <div>
            <h1  class="my_prod_title">{{dept.name}}</h1>

        </div>
    </div>
</div>
</div>
</div>

templates/form.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

 <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'newapp:department' %}"></a></li>
              {% for c in links %}
            <li><a class="dropdown-item" href="{{c.get_url}}">{{c.name}}</a></li>
              {% endfor %}
          </ul>





<form method="post" id="StudentForm" data-branches-url="{% url 'newapp:add' %}" novalidate>
    {% csrf_token %}

      {{ form.as_table }}


        <button type="submit">Save</button>


  </form>
{% for msg in messages %}
{{msg}}
{% endfor %}<br>


<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>


{% endblock %}

templates/test.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link href="{% static 'css/bootstrap.rtl.min.css'%}" rel="stylesheet">
<!--    <meta name="description" content="{% block metadescription %}{% endblock %}">-->

    <title></title>
</head>
<body>
<div class="container">

      <label for="course">Department</label>
              <select class="form-select" id="course" onchange="coursefield()">
                  <option selected>Choose Course</option>
                  {% for i in course %}
                    <option value="{{i.id}}"{% if request.GET.course == i.id|lower %} selected {% endif %}>
                      {{i.name}}
                    </option>
                  {% endfor %}
              </select>
              <br>


              <label for="department">Course</label>
              <select class="form-select" id="department" >
                  <option selected>Choose Department</option>
                  {% for i in department %}
                    <option value="{{i.id}}">
                      {{i.name}}
                     </option>
                  {% endfor %}
              </select>
              <br>

        <script src="{% static 'js/form.js' %}"></script>
</div>



</body>
</html>